export const ELEMENT = {
  SLOT: 'slot',
  TEXT: 'text',
  INPUT: 'input',
  PASSWORD: 'password',
  SELECT: 'select',
  CASCADER: 'cascader',
  TREE_SELECT: 'tree-select',
  DATE_PICKER: 'date-picker',
  NUMBER_WITH_UNIT: 'number-with-unit',
  CHECKBOX: 'checkbox',
  RADIO: 'radio',
  FILE_LIST: 'file-list',
  SWITCH: 'switch',
  RATE: 'rate',
  SINGLE_IMG_UPLOAD: 'single-img-upload',
}
